In [1]:
from commonfunctions import *
import numpy as np
import skimage.io as io
import matplotlib.pyplot as plt
from skimage.color import rgb2gray
from scipy import signal
from skimage.transform import rescale, resize, downscale_local_mean
import math
import os
from skimage.morphology import binary_erosion, binary_dilation
import cv2

In [2]:
def my_resize(img, w, h):
    new_img = np.zeros(shape=(w, h))
    width,height = img.shape
    Xwmin = 0
    Ywmin = 0
    Xwmax = width - 1
    Ywmax = height - 1
    Xvmin = 0
    Yvmin = 0
    Xvmax = w - 1
    Yvmax = h - 1
    Sx = (Xvmax - Xvmin)/(Xwmax - Xwmin)
    Sy = (Yvmax - Yvmin)/(Ywmax - Ywmin)
    for i in range(height):
        new_i = int(Yvmin + (i - Ywmin) * Sy)
        for j in range(width):
            new_j = int(Xvmin + (j - Xwmin) * Sx)
            new_img[new_j][new_i] = img[j][i]
            new_img[new_j][new_i] = img[j][i]
            new_img[new_j][new_i] = img[j][i]
    return new_img      



# image = cv2.imread('Arabic letters/letters/tah/tah.jpg')
# print(image)
# img_resized = my_resize(image, 40, 40)
# show_images([image,img_resized])

In [3]:
def char_calculations(A, width, height):
    A_mean = A.mean()
    col_A = 0
    corr_A = 0
    sum_list = np.zeros(shape=(height,width))
    img_row = 0
    while img_row < height:
        img_col = 0
        while img_col < width:
            col_A += (A[img_row, img_col] - A_mean) ** 2
            sum_list[img_row][img_col] = abs(A[img_row, img_col] - A_mean)
            img_col = img_col + 1
        corr_A += col_A
        col_A = 0
        img_row = img_row + 1  
    return corr_A,sum_list  

In [23]:
width = 30
height = 40

class character:
    def __init__(self, char, template):
        self.char = char
        self.template = cv2.imread(template, 0)
        self.col_sum = np.zeros(shape=(height,width))
        self.corr = 0
        
        

database_characters = []

# Letters
Alf = character("alf", 'Final_All_pgm_charachters_inNumbersSequence/alf3.jpg')
Sen = character("sen", 'Final_All_pgm_charachters_inNumbersSequence/sen.jpg')
Non = character("non", 'Final_All_pgm_charachters_inNumbersSequence/non2.png')
Yeh = character("yeh", 'Final_All_pgm_charachters_inNumbersSequence/yeh.jpg')
Lam = character("lam", 'Final_All_pgm_charachters_inNumbersSequence/lam2.jpg')
Bih = character("bih", 'Final_All_pgm_charachters_inNumbersSequence/30.jpg')
Dal = character("Dal", 'Final_All_pgm_charachters_inNumbersSequence/32.jpg')
Reh = character("reh", 'Final_All_pgm_charachters_inNumbersSequence/36.jpg')
Kaf = character("kaf", 'Final_All_pgm_charachters_inNumbersSequence/86.jpg')
Mim = character("mim", 'Final_All_pgm_charachters_inNumbersSequence/33.jpg')
Waw = character("waw", 'Final_All_pgm_charachters_inNumbersSequence/7.jpg')
Tah = character("tah", 'Final_All_pgm_charachters_inNumbersSequence/82.jpg')
Sad = character("sad", 'Final_All_pgm_charachters_inNumbersSequence/42.jpg')
Gem = character("gem", 'Final_All_pgm_charachters_inNumbersSequence/102.jpg')
Ein = character("ein", 'Final_All_pgm_charachters_inNumbersSequence/ein.png')
Heh = character("heh", 'Final_All_pgm_charachters_inNumbersSequence/heh3.png')
Fih = character("Fih", 'Final_All_pgm_charachters_inNumbersSequence/fih3.png')
Yeh = character("yeh", 'Final_All_pgm_charachters_inNumbersSequence/yeh.jpg')

Alf.template = my_resize(Alf.template, width, height)
Sen.template = my_resize(Sen.template, width, height)
Non.template = my_resize(Non.template, width, height)
Yeh.template = my_resize(Yeh.template, width, height)
Lam.template = my_resize(Lam.template, width, height)
Bih.template = my_resize(Bih.template, width, height)
Dal.template = my_resize(Dal.template, width, height)
Reh.template = my_resize(Reh.template, width, height)
Kaf.template = my_resize(Kaf.template, width, height)
Mim.template = my_resize(Mim.template, width, height)
Waw.template = my_resize(Waw.template, width, height)
Tah.template = my_resize(Tah.template, width, height)
Sad.template = my_resize(Sad.template, width, height)
Gem.template = my_resize(Gem.template, width, height)
Ein.template = my_resize(Ein.template, width, height)
Heh.template = my_resize(Heh.template, width, height)
Fih.template = my_resize(Fih.template, width, height)
Yeh.template = my_resize(Yeh.template, width, height)


Alf.corr, Alf.col_sum = char_calculations(Alf.template, height, width)
Sen.corr, Sen.col_sum = char_calculations(Sen.template, height, width)
Non.corr, Non.col_sum = char_calculations(Non.template, height, width)
Yeh.corr, Yeh.col_sum = char_calculations(Yeh.template, height, width)
Lam.corr, Lam.col_sum = char_calculations(Lam.template, height, width)
Bih.corr, Bih.col_sum = char_calculations(Bih.template, height, width)
Dal.corr, Dal.col_sum = char_calculations(Dal.template, height, width)
Reh.corr, Reh.col_sum = char_calculations(Reh.template, height, width)
Kaf.corr, Kaf.col_sum = char_calculations(Kaf.template, height, width)
Mim.corr, Mim.col_sum = char_calculations(Mim.template, height, width)
Waw.corr, Waw.col_sum = char_calculations(Waw.template, height, width)
Tah.corr, Tah.col_sum = char_calculations(Tah.template, height, width)
Sad.corr, Sad.col_sum = char_calculations(Sad.template, height, width)
Gem.corr, Gem.col_sum = char_calculations(Gem.template, height, width)
Ein.corr, Ein.col_sum = char_calculations(Ein.template, height, width)
Heh.corr, Heh.col_sum = char_calculations(Heh.template, height, width)
Fih.corr, Fih.col_sum = char_calculations(Fih.template, height, width)
Yeh.corr, Yeh.col_sum = char_calculations(Yeh.template, height, width)


# Numbers
One = character("1", 'Final_All_pgm_charachters_inNumbersSequence/3.jpg')
Two = character("2", 'Final_All_pgm_charachters_inNumbersSequence/4.jpg')
Three = character("3", 'Final_All_pgm_charachters_inNumbersSequence/8.jpg')
Four = character("4", 'Final_All_pgm_charachters_inNumbersSequence/11.jpg')
Five = character("5", 'Final_All_pgm_charachters_inNumbersSequence/15.jpg')
Six = character("6", 'Final_All_pgm_charachters_inNumbersSequence/18.jpg')
Seven = character("7", 'Final_All_pgm_charachters_inNumbersSequence/21.jpg')
Eight = character("8", 'Final_All_pgm_charachters_inNumbersSequence/25.jpg')
Nine = character("9", 'Final_All_pgm_charachters_inNumbersSequence/27.jpg')



One.template = my_resize(One.template, width, height)
Two.template = my_resize(Two.template, width, height)
Three.template = my_resize(Three.template, width, height)
Four.template = my_resize(Four.template, width, height)
Five.template = my_resize(Five.template, width, height)
Six.template = my_resize(Six.template, width, height)
Seven.template = my_resize(Seven.template, width, height)
Eight.template = my_resize(Eight.template, width, height)
Nine.template = my_resize(Nine.template, width, height)


One.corr, One.col_sum = char_calculations(One.template, height, width)
Two.corr, Two.col_sum = char_calculations(Two.template, height, width)
Three.corr, Three.col_sum = char_calculations(Three.template, height, width)
Four.corr, Four.col_sum = char_calculations(Four.template, height, width)
Five.corr, Five.col_sum = char_calculations(Five.template, height, width)
Six.corr, Six.col_sum = char_calculations(Six.template, height, width)
Seven.corr, Seven.col_sum = char_calculations(Seven.template, height, width)
Eight.corr, Eight.col_sum = char_calculations(Eight.template, height, width)
Nine.corr, Nine.col_sum = char_calculations(Nine.template, height, width)

# Add to database
database_characters.append(Alf)
database_characters.append(Bih)
database_characters.append(Dal)
database_characters.append(Reh)
database_characters.append(Sen)
database_characters.append(Kaf)
database_characters.append(Mim)
database_characters.append(Tah)
database_characters.append(Sad)
database_characters.append(Waw)
database_characters.append(Gem)
database_characters.append(Lam)
database_characters.append(Yeh)
database_characters.append(Non)
database_characters.append(Ein)
database_characters.append(Heh)
database_characters.append(Fih)
database_characters.append(Yeh)


# database_characters.append(One)
# database_characters.append(Two)
# database_characters.append(Three)
# database_characters.append(Four)
# database_characters.append(Five)
# database_characters.append(Six)
# database_characters.append(Seven)
# database_characters.append(Eight)
# database_characters.append(Nine)



In [9]:
def cal_corr(corr_A, corr_B, A_sum, B_sum):
    corr_both = np.multiply(A_sum, B_sum)
    corr_both = corr_both.sum()
    r = corr_both / math.sqrt(corr_A * corr_B)
    return r

In [24]:

width = 30
height = 40
for i in os.listdir('Arabic letters/letters/alf/'):
    Unk_char = character('Unk','Arabic letters/letters/alf/' + i)
    Unk_char.template = my_resize(Unk_char.template, width, height)
    Unk_char.corr, Unk_char.col_sum = char_calculations(Unk_char.template, height, width)
    r = -1
    curr_r = -1
    for j in database_characters:
        curr_r = cal_corr(Unk_char.corr, j.corr, Unk_char.col_sum, j.col_sum)
        if curr_r > r:
            Unk_char.char = j.char
            r = curr_r
    print(Unk_char.char)


alf
alf
alf
gem
alf
alf
gem
alf
alf
alf
alf
alf
alf
alf
lam
alf
kaf
alf


In [28]:
img = cv2.imread('Final_All_pgm_charachters_inNumbersSequence/alf3.jpg',0)
# img = rgb2gray(img)
# img *= 255
print(img)

[[157.1386 158.1386 158.1386 ... 157.8482 157.8482 156.8482]
 [157.1386 158.1386 158.1386 ... 154.8482 154.8482 153.8482]
 [156.1386 157.1386 159.1386 ... 153.1386 152.1386 152.1386]
 ...
 [150.4991 150.4991 150.4991 ... 154.3529 154.3529 154.3529]
 [150.4991 150.4991 150.4991 ... 153.3529 153.3529 154.3529]
 [150.4991 150.4991 150.4991 ... 152.3529 152.3529 152.3529]]
